development:
  adapter: postgresql
  encoding: unicode
  database: sitescamp_development
  pool: 5
  username: nimbo
  password: 123456
  host: localhost
  port: 5432
production:
  adapter: postgresql
  encoding: unicode
  database: sitescamp_development
  pool: 5
  username: nimbo
  password: 123456
  host: localhost
  port: 5432